name: Setup Fast Down
description: Install fast-down CLI, rename to fd, and add to PATH
author: share121
branding:
  icon: download
  color: blue

inputs:
  version:
    description: 'Version to install (e.g., "latest", "v2.6.2")'
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Detect Platform and Install
      shell: bash
      run: |
        TARGET_OS=""
        case "${{ runner.os }}" in
          "Linux")   TARGET_OS="linux" ;;
          "macOS")   TARGET_OS="macos" ;;
          "Windows") TARGET_OS="windows" ;;
        esac

        TARGET_ARCH=""
        case "${{ runner.arch }}" in
          "X64")   TARGET_ARCH="64bit" ;;
          "ARM64") TARGET_ARCH="arm64" ;;
          "X86")   TARGET_ARCH="32bit" ;;
        esac

        # æ£€æŸ¥ä¸æ”¯æŒçš„ç»„åˆ (macOS 32bit)
        if [[ "$TARGET_OS" == "macos" && "$TARGET_ARCH" == "32bit" ]]; then
          echo "::error::macOS 32bit is not supported by fast-down."
          exit 1
        fi

        if [[ -z "$TARGET_OS" || -z "$TARGET_ARCH" ]]; then
          echo "::error::Unsupported platform: ${{ runner.os }} ${{ runner.arch }}"
          exit 1
        fi

        REPO="fast-down/cli"
        if [[ "${{ inputs.version }}" == "latest" ]]; then
          DOWNLOAD_URL="https://github.com/$REPO/releases/latest/download/fd-$TARGET_OS-$TARGET_ARCH"
        else
          DOWNLOAD_URL="https://github.com/$REPO/releases/download/${{ inputs.version }}/fd-$TARGET_OS-$TARGET_ARCH"
        fi
        if [[ "$TARGET_OS" == "windows" ]]; then
          DOWNLOAD_URL="${DOWNLOAD_URL}.exe"
        fi

        echo "ðŸš€ Installing fast-down for $TARGET_OS ($TARGET_ARCH)..."
        echo "ðŸ”— Downloading from: $DOWNLOAD_URL"

        # å®‰è£…åˆ°ç”¨æˆ·ç›®å½•ä¸‹çš„ .fast-down/bin
        INSTALL_DIR="$HOME/.fast-down/bin"
        mkdir -p "$INSTALL_DIR"

        BIN_NAME="fd"
        if [[ "$TARGET_OS" == "windows" ]]; then
          BIN_NAME="fd.exe"
        fi

        curl -L --fail "$DOWNLOAD_URL" -o "$INSTALL_DIR/$BIN_NAME"

        if [[ "$TARGET_OS" != "windows" ]]; then
          chmod +x "$INSTALL_DIR/$BIN_NAME"
        fi

        if [[ "$TARGET_OS" == "windows" ]]; then
          # ä½¿ç”¨ cygpath -w å°† /c/Users/... è½¬ä¸º C:\Users\... è¿™æ · PowerShell æ‰èƒ½è¯†åˆ«
          echo "$(cygpath -w "$INSTALL_DIR")" >> $GITHUB_PATH
        else
          echo "$INSTALL_DIR" >> $GITHUB_PATH
        fi

        echo "âœ… fast-down installed successfully as '$BIN_NAME'!"
        echo "ðŸ‘‰ You can now use 'fd' command in subsequent steps."
