name: Setup Fast Down
description: Install fast-down CLI, rename to fd, and add to PATH
author: share121
branding:
  icon: download
  color: blue

inputs:
  version:
    description: 'Version to install (e.g., "latest", "2.6.0", "2.6.1")'
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Detect Platform and Install
      shell: bash
      run: |
        # 1. æ˜ å°„ Runner OS åˆ° URL è·¯å¾„
        # GitHub Runner OS: Linux, Windows, macOS
        TARGET_OS=""
        case "${{ runner.os }}" in
          "Linux")   TARGET_OS="linux" ;;
          "macOS")   TARGET_OS="macos" ;;
          "Windows") TARGET_OS="windows" ;;
        esac

        # 2. æ˜ å°„ Runner Arch åˆ° URL è·¯å¾„
        # GitHub Runner Arch: X64, ARM64, X86
        TARGET_ARCH=""
        case "${{ runner.arch }}" in
          "X64")   TARGET_ARCH="64bit" ;;
          "ARM64") TARGET_ARCH="arm64" ;;
          "X86")   TARGET_ARCH="32bit" ;;
        esac

        # æ£€æŸ¥ä¸æ”¯æŒçš„ç»„åˆ (macOS 32bit)
        if [[ "$TARGET_OS" == "macos" && "$TARGET_ARCH" == "32bit" ]]; then
          echo "::error::macOS 32bit is not supported by fast-down."
          exit 1
        fi

        if [[ -z "$TARGET_OS" || -z "$TARGET_ARCH" ]]; then
          echo "::error::Unsupported platform: ${{ runner.os }} ${{ runner.arch }}"
          exit 1
        fi

        # 3. æž„é€ ä¸‹è½½ URL
        # URL ç»“æž„: https://fast-down-update.s121.top/cli/download/latest/{os}/{arch}
        BASE_URL="https://fast-down-update.s121.top/cli/download"
        VERSION="${{ inputs.version }}"
        DOWNLOAD_URL="$BASE_URL/$VERSION/$TARGET_OS/$TARGET_ARCH"

        echo "ðŸš€ Installing fast-down for $TARGET_OS ($TARGET_ARCH)..."
        echo "ðŸ”— Downloading from: $DOWNLOAD_URL"

        # 4. å‡†å¤‡å®‰è£…è·¯å¾„
        # æˆ‘ä»¬å®‰è£…åˆ°ç”¨æˆ·ç›®å½•ä¸‹çš„ .fast-down/bin
        INSTALL_DIR="$HOME/.fast-down/bin"
        mkdir -p "$INSTALL_DIR"

        # 5. ç¡®å®šæ–‡ä»¶å (Windows éœ€è¦ .exe åŽç¼€)
        BIN_NAME="fd"
        if [[ "$TARGET_OS" == "windows" ]]; then
          BIN_NAME="fd.exe"
        fi

        # 6. ä¸‹è½½å¹¶é‡å‘½å (-L è·Ÿéšé‡å®šå‘, --fail å¤±è´¥æŠ¥é”™)
        # è¿™é‡Œçš„å…³é”®æ˜¯ç›´æŽ¥ä¸‹è½½ä¸ºç›®æ ‡æ–‡ä»¶å $BIN_NAME (fd æˆ– fd.exe)
        curl -L --fail "$DOWNLOAD_URL" -o "$INSTALL_DIR/$BIN_NAME"

        # 7. èµ‹äºˆæ‰§è¡Œæƒé™ (éž Windows)
        if [[ "$TARGET_OS" != "windows" ]]; then
          chmod +x "$INSTALL_DIR/$BIN_NAME"
        fi

        # 8. æ·»åŠ åˆ° GitHub Actions çš„ PATH
        echo "$INSTALL_DIR" >> $GITHUB_PATH

        echo "âœ… fast-down installed successfully as '$BIN_NAME'!"
        echo "ðŸ‘‰ You can now use 'fd' command in subsequent steps."
